// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKULEjMRRIiSUtGyS3FcHEUgLJ5OMnK7Q',
    appId: '1:390018716723:web:6375cbe32759e1436c7f46',
    messagingSenderId: '390018716723',
    projectId: 'carhub-c29dc',
    authDomain: 'carhub-c29dc.firebaseapp.com',
    storageBucket: 'carhub-c29dc.appspot.com',
    measurementId: 'G-KGM11P9LJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9rz0r0hsmR3djP6_nuLw3f71R1DPmxjQ',
    appId: '1:390018716723:android:727a942a14e846546c7f46',
    messagingSenderId: '390018716723',
    projectId: 'carhub-c29dc',
    storageBucket: 'carhub-c29dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaO0JbUYAs6qineMkTzjZTVz8f6B8RmpE',
    appId: '1:390018716723:ios:0f823065176ccd996c7f46',
    messagingSenderId: '390018716723',
    projectId: 'carhub-c29dc',
    storageBucket: 'carhub-c29dc.appspot.com',
    iosBundleId: 'com.example.cars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaO0JbUYAs6qineMkTzjZTVz8f6B8RmpE',
    appId: '1:390018716723:ios:0f823065176ccd996c7f46',
    messagingSenderId: '390018716723',
    projectId: 'carhub-c29dc',
    storageBucket: 'carhub-c29dc.appspot.com',
    iosBundleId: 'com.example.cars',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKULEjMRRIiSUtGyS3FcHEUgLJ5OMnK7Q',
    appId: '1:390018716723:web:6abe04d2dc0afd946c7f46',
    messagingSenderId: '390018716723',
    projectId: 'carhub-c29dc',
    authDomain: 'carhub-c29dc.firebaseapp.com',
    storageBucket: 'carhub-c29dc.appspot.com',
    measurementId: 'G-E3FP9ML46K',
  );
}
